name: Build and push docker images for backend

on:
  push:
    branches: [master]

env:
  DOCKER_REGISTRY: aipipeline

jobs:
  api-server:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        run: echo "TAG=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      -
        name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: backend/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/api-server:${{ env.TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  persistenceagent:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        run: echo "TAG=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      -
        name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: backend/Dockerfile.persistenceagent
          tags: ${{ env.DOCKER_REGISTRY }}/persistenceagent:${{ env.TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  metadata-writer:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        run: echo "TAG=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      -
        name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: backend/metadata_writer/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/metadata-writer:${{ env.TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  scheduledworkflow:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        run: echo "TAG=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      -
        name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: backend/Dockerfile.scheduledworkflow
          tags: ${{ env.DOCKER_REGISTRY }}/scheduledworkflow:${{ env.TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}