name: Build and push docker images for backend

on:
  push:
    branches: [master]

env:
  DOCKER_REGISTRY: aipipeline
  IMAGE_TAG: latest

jobs:
  api-server:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/build-push-action@v2
        with:
          push: true
          file: backend/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/api-server:${{ env.IMAGE_TAG }}
  persistenceagent:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/build-push-action@v2
        with:
          push: true
          file: backend/Dockerfile.persistenceagent
          tags: ${{ env.DOCKER_REGISTRY }}/persistenceagent:${{ env.IMAGE_TAG }}
  metadata-writer:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/build-push-action@v2
        with:
          push: true
          file: backend/metadata_writer/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/metadata-writer:${{ env.IMAGE_TAG }}
  scheduledworkflow:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/build-push-action@v2
        with:
          push: true
          file: backend/Dockerfile.scheduledworkflow
          tags: ${{ env.DOCKER_REGISTRY }}/scheduledworkflow:${{ env.IMAGE_TAG }}
